name: AIZM Go Server 

on:
  push:
    branches:
      - krimaster

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.password }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: . 
          push: true
          tags: ${{ github.actor }}/${{ github.repository }}:1.3
